---
#
# Ansible managed
#
repository:
  description: Install and configure httpd on your system.
  homepage: https://buluma.github.io/
  topics: webserver, apache, httpd, installer, package, system, networking, ansible, molecule, tox, playbook
