---
image: "buluma/github-action-molecule:4.0.5"

services:
  - docker:dind

variables:
  DOCKER_HOST: "tcp://docker:2375"
  PY_COLORS: 1

molecule:
  script:
    - image=${image} tag=${tag} molecule test
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
  retry: 1
  parallel:
    matrix:
      - image: "fedora"
        tag: "34"
      - image: "fedora"
        tag: "latest"
      - image: "fedora"
        tag: "rawhide"

testing:
  script:
    - image=${image} tag=${tag} molecule test
  rules:
    - if: $CI_COMMIT_REF_NAME == "testing"
  retry: 1
  parallel:
    matrix:
      - image: "fedora"
        tag: "34"
      - image: "fedora"
        tag: "latest"
      - image: "fedora"
        tag: "rawhide"

galaxy:
  script:
    - ansible-galaxy role info ${CI_PROJECT_NAMESPACE}.httpd

build:
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - git clone https://github.com/buluma/ansible-role-httpd.git && cd ansible-role-httpd
    - docker build -t $CI_REGISTRY/group/project/image:latest .
    - docker push $CI_REGISTRY/group/project/image:latest
