---
roles:
  - name: buluma.bootstrap
  - name: buluma.buildtools
  - name: buluma.epel
  - name: buluma.openssl
  - name: buluma.python_pip
  - name: robertdebock.selinux
collections:
  - name: ansible.posix
  - name: community.crypto
  - name: community.general
