---
name: GitLab Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Login to Docker
      run: docker login registry.gitlab.com -u buluma -p ${{ secrets.GITLAB_PASSWORD }}

    - name: Build Image
      run: docker build -t registry.gitlab.com/buluma/ansible-role-httpd .